### ISSUE TITLE
phone

### ISSUE THREAD

**Issue by Lucrecia814** [forever585/mouse#10]
I have no money to verifiy account phone for linkedin and any others.
Plz send me some ap

**Comment by forever585** [comment]
I didn't finish that task.
If I can get some money I will send you, or will post a project.

**Comment by Lucrecia814** [comment]
One 
I have one skype
Do you have skype on your side you can?
I can provide one which registered on your side.

**Comment by forever585** [comment]
Thank you.
I registered some skype, just before and I think we can keep connection with it.
And are you having freelancer.com account?

**Comment by Lucrecia814** [comment]
fake account 
there are so many fake account i have

**Comment by forever585** [comment]
calling
from apple
